import Head from 'next/head';

import SideBar from '../components/sidebar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* sidebar starts here */}
      <div className='w-full h-auto'>
        <SideBar></SideBar>
      </div>
    </div>
  );
}
